# Generated by Django 4.1.2 on 2022-10-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_isapproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='isApproved',
        ),
        migrations.AddField(
            model_name='album',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approve the album if its name is not explicit'),
        ),
    ]
