# Generated by Django 4.1.2 on 2022-10-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['stage_name']},
        ),
    ]
